export const ADD_GOAL_START = "ADD_GOAL_START";
export const ADD_GOAL_SUCCESS = "ADD_GOAL_SUCCESS";
export const ADD_GOAL_FAIL = "ADD_GOAL_FAIL";

export const GET_GOALS_START = "GET_GOALS_START";
export const GET_GOALS_SUCCESS = "GET_GOALS_SUCCESS";
export const GET_GOALS_FAIL = "GET_GOALS_FAIL";

export const DELETE_GOAL_START = "DELETE_GOAL_START";
export const DELETE_GOAL_SUCCESS = "DELETE_GOAL_SUCCESS";
export const DELETE_GOAL_FAIL = "DELETE_GOAL_FAIL";

export const UPDATE_GOAL_START = "UPDATE_GOAL_START";
export const UPDATE_GOAL_SUCCESS = "UPDATE_GOAL_SUCCESS";
export const UPDATE_GOAL_FAIL = "UPDATE_GOAL_FAIL";
